name: Run weekly cleanup
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - uses: actions/checkout@v2
      - run: python ${GITHUB_WORKSPACE}/scripts/cleanup_data.py
      - name: Commit structure to git repo
        uses: EndBug/add-and-commit@v9
        with:
          message: Limpieza automática
          author_name: javi-aranda
          committer_name: javi-aranda
          commit: --signoff
