name: data
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Set up datetime variables
        id: date
        run: |
          echo "::set-output name=year::$(date +'%Y')"
          echo "::set-output name=month::$(date +'%m')"
          echo "::set-output name=day::$(date +'%d')"
          echo "::set-output name=time::$(date +'%H:%M)"
      - name: Set up dir variables
        id: dir
        run: |          
          echo "::set-output name=dir::${{ steps.date.outputs.date }}/${{ steps.date.outputs.month }}/${{ steps.date.outputs.day }}"
      - name: Create directory structure
        run: |
          mkdir -p ${{ steps.dir.outputs.dir }}
      - name: Write .gitkeep file
        run: |
          touch ${{ steps.dir.outputs.dir }}/.gitkeep
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://datosabiertos.malaga.eu/recursos/aparcamientos/ocupappublicosmun/ocupappublicosmun.csv
          downloaded_filename: |
            ${{ steps.dir.outputs.dir }}/parking-data-${{ steps.date.outputs.time }}.csv
