name: data
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up datetime variables
        id: date
        run: |
          echo "::set-output name=year::$(date +'%Y')"
          echo "::set-output name=month::$(date +'%m')"
          echo "::set-output name=day::$(date +'%d')"
          echo "::set-output name=time::$(date +'%H_%M')"
      - name: Set up dir variables
        id: dir
        run: |          
          echo "::set-output name=dir::${{ steps.date.outputs.year }}/${{ steps.date.outputs.month }}/${{ steps.date.outputs.day }}"
      - name: Create directory structure
        run: |
          mkdir -p ${{ github.workspace }}${{ steps.dir.outputs.dir }}
      - name: Write .gitkeep file
        run: |
          touch ${{ github.workspace }}${{ steps.dir.outputs.dir }}/.gitkeep
      - name: Commit structure to git repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Estructura generada automáticamente
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: javisenberg
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://datosabiertos.malaga.eu/recursos/aparcamientos/ocupappublicosmun/ocupappublicosmun.csv
          downloaded_filename: |
            parking-data-${{ steps.date.outputs.time }}.csv
      - name: Move data to directory
        run: |
          mv parking-data-${{ steps.date.outputs.time }}.csv ${{ github.workspace }}${{ steps.dir.outputs.dir }}
      - name: Update file location
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Estructura generada automáticamente
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: javisenberg
