name: Retrieve latest data and update repository
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up datetime variables
        id: date
        run: |
          echo "year=$(date +'%Y')" >> "$GITHUB_ENV"
          echo "month=$(date +'%m')" >> "$GITHUB_ENV"
          echo "day=$(date +'%d')" >> "$GITHUB_ENV"
          echo "time=$(date +'%H_%M')" >> "$GITHUB_ENV"
        env:
          TZ: /usr/share/zoneinfo/Europe/Madrid
      - name: Set up dir variables
        id: dir
        run: |
          echo "dir=$year/$month/$day" >> "$GITHUB_ENV"
      - name: Create directory structure
        run: |
          mkdir -p ${{ github.workspace }}/$dir
      - name: Write .gitkeep file
        run: |
          touch ${{ github.workspace }}/$dir/.gitkeep
      - name: Commit structure to git repo
        uses: EndBug/add-and-commit@v9
        with:
          message: Estructura generada automáticamente
          author_name: javi-aranda
          committer_name: javi-aranda
          commit: --signoff
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://datosabiertos.malaga.eu/recursos/aparcamientos/ocupappublicosmun/ocupappublicosmun.csv
          downloaded_filename: |
            latest.csv
        continue-on-error: true
      - name: Move data to directory
        run: |
          cp latest.csv ${{ github.workspace }}/$dir/parking-data-$time.csv
      - name: Update file location
        uses: EndBug/add-and-commit@v9
        with:
          message: Estructura generada automáticamente
          author_name: javi-aranda
          committer_name: javi-aranda
          commit: --signoff
