name: retrieve latest data and update repository
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up datetime variables
        id: date
        run: |
          echo "::set-output name=year::$(date +'%Y')"
          echo "::set-output name=month::$(date +'%m')"
          echo "::set-output name=day::$(date +'%d')"
          echo "::set-output name=time::$(date +'%H_%M')"
        env:
          TZ: /usr/share/zoneinfo/Europe/Madrid
      - name: Set up dir variables
        id: dir
        run: |          
          echo "::set-output name=dir::${{ steps.date.outputs.year }}/${{ steps.date.outputs.month }}/${{ steps.date.outputs.day }}"
      - name: Create directory structure
        run: |
          mkdir -p ${{ github.workspace }}/${{ steps.dir.outputs.dir }}
      - name: Write .gitkeep file
        run: |
          touch ${{ github.workspace }}/${{ steps.dir.outputs.dir }}/.gitkeep
      - name: Commit structure to git repo
        uses: EndBug/add-and-commit@v9
        with:
          message: Estructura generada automáticamente
          author_name: javi-aranda
          committer_name: javi-aranda
          commit: --signoff
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://datosabiertos.malaga.eu/recursos/aparcamientos/ocupappublicosmun/ocupappublicosmun.csv
          downloaded_filename: |
            latest.csv
        continue-on-error: true
      - name: Move data to directory
        run: |
          cp latest.csv ${{ github.workspace }}/${{ steps.dir.outputs.dir }}/parking-data-${{ steps.date.outputs.time }}.csv
      - name: Update file location
        uses: EndBug/add-and-commit@v9
        with:
          message: Estructura generada automáticamente
          author_name: javi-aranda
          committer_name: javi-aranda
          commit: --signoff
